// <auto-generated />
using System;
using FCEService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCEService.Migrations
{
    [DbContext(typeof(FCEDbContext))]
    [Migration("20260710073040_SeedFitnessPlanConfig")]
    partial class SeedFitnessPlanConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCEService.Domain.Entities.CalculatedMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Bmr")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<double>("CalorieTarget")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Tdee")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UIX_CalculatedMetrics_UserId");

                    b.ToTable("CalculatedMetrics", (string)null);
                });

            modelBuilder.Entity("FCEService.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.Property<string>("PlanId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EstimatedDuration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("MaxCalorie")
                        .HasColumnType("float");

                    b.Property<double>("MinCalorie")
                        .HasColumnType("float");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WorkoutsPerWeek")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.ToTable("FitnessPlanConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            PlanId = "lose-weight-weak",
                            Description = "Low-intensity plan for users with low calorie targets aiming to lose weight.",
                            EstimatedDuration = "8 weeks",
                            Goal = "LoseWeight",
                            MaxCalorie = 1800.0,
                            MinCalorie = 0.0,
                            PlanName = "Gentle Fat Loss",
                            ProgramType = "Low-Impact Cardio",
                            Status = "Weak",
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            PlanId = "lose-weight-normal",
                            Description = "Moderate-intensity plan for users with a normal calorie target aiming to lose weight.",
                            EstimatedDuration = "8 weeks",
                            Goal = "LoseWeight",
                            MaxCalorie = 2500.0,
                            MinCalorie = 1801.0,
                            PlanName = "Balanced Fat Loss",
                            ProgramType = "Cardio + Strength",
                            Status = "Normal",
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            PlanId = "lose-weight-hard",
                            Description = "High-intensity plan for users with a high calorie target aiming to lose weight.",
                            EstimatedDuration = "10 weeks",
                            Goal = "LoseWeight",
                            MaxCalorie = 1.7976931348623157E+308,
                            MinCalorie = 2501.0,
                            PlanName = "Intensive Fat Loss",
                            ProgramType = "HIIT + Strength",
                            Status = "Hard",
                            WorkoutsPerWeek = 5
                        },
                        new
                        {
                            PlanId = "get-fitter-weak",
                            Description = "Entry-level general fitness plan for low calorie targets.",
                            EstimatedDuration = "6 weeks",
                            Goal = "GetFitter",
                            MaxCalorie = 1800.0,
                            MinCalorie = 0.0,
                            PlanName = "Foundation Fitness",
                            ProgramType = "Full-Body Basics",
                            Status = "Weak",
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            PlanId = "get-fitter-normal",
                            Description = "Balanced general fitness plan for normal calorie targets.",
                            EstimatedDuration = "8 weeks",
                            Goal = "GetFitter",
                            MaxCalorie = 2500.0,
                            MinCalorie = 1801.0,
                            PlanName = "General Fitness",
                            ProgramType = "Full-Body + Cardio",
                            Status = "Normal",
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            PlanId = "get-fitter-hard",
                            Description = "Advanced general fitness plan for high calorie targets.",
                            EstimatedDuration = "10 weeks",
                            Goal = "GetFitter",
                            MaxCalorie = 1.7976931348623157E+308,
                            MinCalorie = 2501.0,
                            PlanName = "Advanced Fitness",
                            ProgramType = "Full-Body + HIIT",
                            Status = "Hard",
                            WorkoutsPerWeek = 5
                        },
                        new
                        {
                            PlanId = "gain-weight-weak",
                            Description = "Entry-level muscle gain plan for low calorie targets.",
                            EstimatedDuration = "10 weeks",
                            Goal = "GainWeight",
                            MaxCalorie = 1800.0,
                            MinCalorie = 0.0,
                            PlanName = "Lean Bulk Starter",
                            ProgramType = "Strength Foundations",
                            Status = "Weak",
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            PlanId = "gain-weight-normal",
                            Description = "Balanced muscle gain plan for normal calorie targets.",
                            EstimatedDuration = "12 weeks",
                            Goal = "GainWeight",
                            MaxCalorie = 2500.0,
                            MinCalorie = 1801.0,
                            PlanName = "Lean Bulk",
                            ProgramType = "Hypertrophy Strength",
                            Status = "Normal",
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            PlanId = "gain-weight-hard",
                            Description = "Advanced muscle gain plan for high calorie targets.",
                            EstimatedDuration = "12 weeks",
                            Goal = "GainWeight",
                            MaxCalorie = 1.7976931348623157E+308,
                            MinCalorie = 2501.0,
                            PlanName = "Mass Gain",
                            ProgramType = "Heavy Strength + Volume",
                            Status = "Hard",
                            WorkoutsPerWeek = 5
                        },
                        new
                        {
                            PlanId = "gain-more-flexible-weak",
                            Description = "Entry-level flexibility/mobility plan for low calorie targets.",
                            EstimatedDuration = "6 weeks",
                            Goal = "GainMoreFlexible",
                            MaxCalorie = 1800.0,
                            MinCalorie = 0.0,
                            PlanName = "Mobility Starter",
                            ProgramType = "Mobility + Stretching",
                            Status = "Weak",
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            PlanId = "gain-more-flexible-normal",
                            Description = "Balanced flexibility/mobility plan for normal calorie targets.",
                            EstimatedDuration = "8 weeks",
                            Goal = "GainMoreFlexible",
                            MaxCalorie = 2500.0,
                            MinCalorie = 1801.0,
                            PlanName = "Flexibility & Mobility",
                            ProgramType = "Yoga + Mobility",
                            Status = "Normal",
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            PlanId = "gain-more-flexible-hard",
                            Description = "Advanced flexibility/mobility plan for high calorie targets.",
                            EstimatedDuration = "10 weeks",
                            Goal = "GainMoreFlexible",
                            MaxCalorie = 1.7976931348623157E+308,
                            MinCalorie = 2501.0,
                            PlanName = "Advanced Mobility",
                            ProgramType = "Dynamic Mobility + Strength",
                            Status = "Hard",
                            WorkoutsPerWeek = 5
                        },
                        new
                        {
                            PlanId = "learn-the-basic-weak",
                            Description = "Introductory plan teaching fundamentals for low calorie targets.",
                            EstimatedDuration = "6 weeks",
                            Goal = "LearnTheBasic",
                            MaxCalorie = 1800.0,
                            MinCalorie = 0.0,
                            PlanName = "Beginner Basics",
                            ProgramType = "Fundamentals",
                            Status = "Weak",
                            WorkoutsPerWeek = 2
                        },
                        new
                        {
                            PlanId = "learn-the-basic-normal",
                            Description = "Standard fundamentals plan for normal calorie targets.",
                            EstimatedDuration = "8 weeks",
                            Goal = "LearnTheBasic",
                            MaxCalorie = 2500.0,
                            MinCalorie = 1801.0,
                            PlanName = "Core Basics",
                            ProgramType = "Fundamentals + Cardio",
                            Status = "Normal",
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            PlanId = "learn-the-basic-hard",
                            Description = "Fundamentals plan with added intensity for high calorie targets.",
                            EstimatedDuration = "8 weeks",
                            Goal = "LearnTheBasic",
                            MaxCalorie = 1.7976931348623157E+308,
                            MinCalorie = 2501.0,
                            PlanName = "Applied Basics",
                            ProgramType = "Fundamentals + Strength",
                            Status = "Hard",
                            WorkoutsPerWeek = 4
                        });
                });

            modelBuilder.Entity("FCEService.Domain.Entities.UserAssignedPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserAssignedPlans_UserId");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_UserAssignedPlans_UserId_IsActive");

                    b.ToTable("UserAssignedPlans", (string)null);
                });

            modelBuilder.Entity("FCEService.Domain.Entities.UserFitnessStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserFitnessStats_UserId");

                    b.ToTable("UserFitnessStats", (string)null);
                });

            modelBuilder.Entity("FCEService.Domain.Entities.UserPlanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReasonForChange")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserPlanHistories_UserId");

                    b.ToTable("UserPlanHistories", (string)null);
                });

            modelBuilder.Entity("FCEService.Domain.Entities.UserAssignedPlan", b =>
                {
                    b.HasOne("FCEService.Domain.Entities.FitnessPlanConfig", "FitnessPlanConfig")
                        .WithMany("UserAssignedPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FitnessPlanConfig");
                });

            modelBuilder.Entity("FCEService.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.Navigation("UserAssignedPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
